name: CI

on: 
  push:
  pull_request:
    branches:
      master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
      run: npm run build
